# Generated by Django 5.0.3 on 2024-03-13 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('liter', models.FloatField(blank=True, null=True)),
                ('name_uz', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('description_uz', models.CharField(max_length=300)),
                ('description_ru', models.CharField(max_length=300)),
                ('description_en', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='food')),
                ('price', models.IntegerField()),
                ('tax_code', models.IntegerField(blank=True, null=True)),
                ('warehouse_code', models.IntegerField(blank=True, null=True)),
                ('branches', models.ManyToManyField(blank=True, null=True, to='admins.branches')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('related_category', models.ManyToManyField(blank=True, null=True, related_name='related_category', to='product.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
